basePath: /v1
definitions:
  handler.pingResponse:
    properties:
      result:
        type: string
    type: object
host: localhost:4343
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample chi server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /v1/ping:
    get:
      description: Pings the API and gets response back
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.pingResponse'
        "429":
          description: Rate limit exceeded
          schema:
            type: string
      summary: Ping the API
swagger: "2.0"
